### ISSUE TITLE
Can't move joystick of said game while pressing a game button

### ISSUE THREAD

**Issue by Thekidiacs** [IrPgFKS0/ZXTouch-Python-Client#4]
So if I am moving forward and want to jump while moving forward the joystick will stop moving and jump with no jumping forward effect. Don't know if this can be fixed. But it renders the gameplay unplayable. Hope you can help me out with this.

**Comment by Thekidiacs** [comment]
If you need a screenshot/video of what my config.json is and what it actually looks like on my iPad let me know.

**Comment by Thekidiacs** [comment]
Also, I mapped the joystick center to the center of the joystick and put w on the north part of the joystick d for east part, a for west and d for south.

**Comment by IrPgFKS0** [comment]
It sounds like the joystick mapping is not synced with your game, please send me your mapping and video.
